# Generated by Django 5.0.6 on 2024-06-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_direccion_estado_direccion_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='pais',
        ),
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(choices=[('REGION_LOS_RIOS', 'Región de Los Ríos'), ('REGION_ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('REGION_ATACAMA', 'Región de Atacama'), ('REGION_ANTOFAGASTA', 'Región de Antofagasta'), ('REGION_ARAUCANIA', 'Región de La Araucanía'), ('REGION_AISEN', 'Región Aisén del General Carlos Ibáñez del Campo'), ('REGION_BERNARDO_OHIGGINS', "Región del Libertador General Bernardo O'Higgins"), ('REGION_NUBLE', 'Región de Ñuble'), ('REGION_MAULE', 'Región del Maule'), ('REGION_BIOBIO', 'Región del Biobío'), ('REGION_COQUIMBO', 'Región de Coquimbo'), ('REGION_TARAPACA', 'Región de Tarapacá'), ('REGION_MAGALLANES', 'Región de Magallanes y de la Antártica Chilena'), ('REGION_VALPARAISO', 'Región de Valparaíso'), ('REGION_METROPOLITANA', 'Región Metropolitana de Santiago'), ('REGION_LOS_LAGOS', 'Región de Los Lagos')], default='REGION_BIOBIO', max_length=100),
        ),
    ]
