# Generated by Django 5.0.6 on 2024-06-30 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_direccion_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(choices=[('REGION_METROPOLITANA', 'Región Metropolitana de Santiago'), ('REGION_BIOBIO', 'Región del Biobío'), ('REGION_ARAUCANIA', 'Región de La Araucanía'), ('REGION_TARAPACA', 'Región de Tarapacá'), ('REGION_ATACAMA', 'Región de Atacama'), ('REGION_MAGALLANES', 'Región de Magallanes y de la Antártica Chilena'), ('REGION_ANTOFAGASTA', 'Región de Antofagasta'), ('REGION_BERNARDO_OHIGGINS', "Región del Libertador General Bernardo O'Higgins"), ('REGION_LOS_RIOS', 'Región de Los Ríos'), ('REGION_COQUIMBO', 'Región de Coquimbo'), ('REGION_MAULE', 'Región del Maule'), ('REGION_AISEN', 'Región Aisén del General Carlos Ibáñez del Campo'), ('REGION_ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('REGION_LOS_LAGOS', 'Región de Los Lagos'), ('REGION_VALPARAISO', 'Región de Valparaíso'), ('REGION_NUBLE', 'Región de Ñuble')], default='REGION_BIOBIO', max_length=100),
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
