# Generated by Django 5.0.6 on 2024-07-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cliente_email_alter_direccion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(choices=[('REGION_LOS_LAGOS', 'Región de Los Lagos'), ('REGION_ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('REGION_METROPOLITANA', 'Región Metropolitana de Santiago'), ('REGION_MAGALLANES', 'Región de Magallanes y de la Antártica Chilena'), ('REGION_NUBLE', 'Región de Ñuble'), ('REGION_BERNARDO_OHIGGINS', "Región del Libertador General Bernardo O'Higgins"), ('REGION_MAULE', 'Región del Maule'), ('REGION_BIOBIO', 'Región del Biobío'), ('REGION_ARAUCANIA', 'Región de La Araucanía'), ('REGION_VALPARAISO', 'Región de Valparaíso'), ('REGION_TARAPACA', 'Región de Tarapacá'), ('REGION_ATACAMA', 'Región de Atacama'), ('REGION_ANTOFAGASTA', 'Región de Antofagasta'), ('REGION_LOS_RIOS', 'Región de Los Ríos'), ('REGION_COQUIMBO', 'Región de Coquimbo'), ('REGION_AISEN', 'Región Aisén del General Carlos Ibáñez del Campo')], default='REGION_BIOBIO', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordenitem',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto'),
        ),
    ]
