# Generated by Django 5.0.6 on 2024-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_direccion_region_alter_ordenitem_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='region',
            field=models.CharField(choices=[('REGION_LOS_RIOS', 'Región de Los Ríos'), ('REGION_AISEN', 'Región Aisén del General Carlos Ibáñez del Campo'), ('REGION_METROPOLITANA', 'Región Metropolitana de Santiago'), ('REGION_ANTOFAGASTA', 'Región de Antofagasta'), ('REGION_NUBLE', 'Región de Ñuble'), ('REGION_VALPARAISO', 'Región de Valparaíso'), ('REGION_MAULE', 'Región del Maule'), ('REGION_ATACAMA', 'Región de Atacama'), ('REGION_ARICA_PARINACOTA', 'Región de Arica y Parinacota'), ('REGION_COQUIMBO', 'Región de Coquimbo'), ('REGION_BIOBIO', 'Región del Biobío'), ('REGION_TARAPACA', 'Región de Tarapacá'), ('REGION_ARAUCANIA', 'Región de La Araucanía'), ('REGION_MAGALLANES', 'Región de Magallanes y de la Antártica Chilena'), ('REGION_LOS_LAGOS', 'Región de Los Lagos'), ('REGION_BERNARDO_OHIGGINS', "Región del Libertador General Bernardo O'Higgins")], default='REGION_BIOBIO', max_length=100),
        ),
    ]
